Adjust user_message, rename local to localai, make each LLM call a function

diff --git a/bin/get_recycle_day_adjustment b/bin/get_recycle_day_adjustment
--- a/bin/get_recycle_day_adjustment
+++ b/bin/get_recycle_day_adjustment
@@ -23,7 +23,7 @@ for var in home_assistant_base_url recycle_url_main recycle_default_day; do
   [[ $var == recycle_url_main ]] && [[ ! $recycle_url_main ]] && recycle_url_main=https://www.montgomerycountymd.gov/DEP/trash-recycling/index.html
   [[ $var == recycle_default_day ]] && [[ ! $recycle_default_day ]] && recycle_default_day=Friday
 done
-for var in min_agree ollama_enabled ollama_model ollama_url ollama_api_key local_enabled local_model local_url local_api_key claude_enabled claude_api_key mistral_enabled mistral_api_key mistral_agent_id chatgpt_enabled chatgpt_api_key hass_api_key; do
+for var in min_agree ollama_enabled ollama_model ollama_url ollama_api_key localai_enabled localai_model localai_prompt localai_url localai_api_key claude_enabled claude_model claude_api_key mistral_enabled mistral_api_key mistral_agent_id chatgpt_enabled chatgpt_model chatgpt_api_key hass_api_key; do
   [[ ! "${!var}" ]] && declare "$var=$(awk "/^recycle_day_$var ?:/{sub(/^[^:]+ *: */,\"\");gsub(/^\"|\"$/,\"\");print}" "$secrets_file")"
   [[ $var =~ _enabled$ ]] && [[ ${!var} != true || ! "${!var}" ]] && declare "$var=false"
   [[ $var == min_agree ]] && [[ ! $min_agree ]] && min_agree=2
@@ -40,7 +40,7 @@ usage() {
   echo "  -t TESTDATE  : Use a test date instead of today (must be YYYY-mm-dd)"
   echo "  -a ANSWER    : Hardcode an answer"
   echo "  -m MIN_AGREE : Minimum number of LLMs must agree on answer (default: $min_agree)"
-  echo "  ENGINE can one of: local, ollama, mistral, claude, or chatgpt"
+  echo "  ENGINE can one of: localai, ollama, mistral, claude, or chatgpt"
   echo "  MODEL has not been implemented yet"
   exit $1
 }
@@ -71,19 +71,19 @@ done
 shift $((OPTIND -1))
 
 if [ -n "$1" ]; then
-  local_enabled=false
+  localai_enabled=false
   ollama_enabled=false
   mistral_enabled=false
   claude_enabled=false
   chatgpt_enabled=false
   min_agree=1
   case "$1" in
-    local)   local_enabled=true ;;
+    localai) localai_enabled=true ;;
     ollama)  ollama_enabled=true ;;
     mistral) mistral_enabled=true ;;
     claude)  claude_enabled=true ;;
     chatgpt) chatgpt_enabled=true ;;
-    * ) echo "Error: Invalid AI engine (must be: local, ollama, mistral, claude, or chatgpt" && exit 1 ;;
+    * ) echo "Error: Invalid AI engine (must be: localai, ollama, mistral, claude, or chatgpt" && exit 1 ;;
   esac
 fi
 
@@ -128,11 +128,12 @@ else
   echo "Warning: Invalid MoCo Alert/Warning URL ($county_alert_url)" > /dev/stderr
 fi
 
-user_message="My normal recycling pickup weekday is $normal_recycle_day and today is $reference_date. $county_alert_text If nothing so far has indicated that the recycling will change this week, then the day the county will pick up my recycle should be the normal recycling pickup weekday. Without explaining how you arrived at your conclusion, what weekday will the county come to pick up my recycle this week?"
+# user_message="My normal recycling pickup weekday is $normal_recycle_day and today is $reference_date. $county_alert_text If nothing so far has indicated that the recycling will change this week, then the day the county will pick up my recycle should be the normal recycling pickup weekday. Without explaining how you arrived at your conclusion, what weekday will the county come to pick up my recycle this week?"
+user_message="My normal recycling pickup weekday is $normal_recycle_day and today is $reference_date. $county_alert_text If nothing so far has indicated that the recycling will change this week, then the day the county will pick up my recycle should be the normal recycling pickup weekday. Briefly tell me which weekday will the county come to pick up my recycle this week?"
 user_message=${user_message/// }
 
 if $debug; then
-  for var in home_assistant_base_url hass_api_key recycle_url_main county_alert_url recycle_default_day normal_recycle_day today_date reference_date min_agree user_message local_enabled local_url local_model local_api_key ollama_enabled ollama_url ollama_model ollama_api_key claude_enabled claude_api_key mistral_enabled mistral_api_key mistral_agent_id chatgpt_enabled chatgpt_api_key; do
+  for var in home_assistant_base_url hass_api_key recycle_url_main county_alert_url recycle_default_day normal_recycle_day today_date reference_date min_agree user_message localai_enabled localai_url localai_model localai_prompt localai_api_key ollama_enabled ollama_url ollama_model ollama_api_key claude_enabled claude_model claude_api_key mistral_enabled mistral_api_key mistral_agent_id chatgpt_enabled chatgpt_model chatgpt_api_key; do
     $debug && printf '%s=%s\n' "$var" "${!var}"
   done
   $debug_exit && exit
@@ -156,16 +157,24 @@ check_agreement() {
   echo $answer
 }
 
-if [[ ! $answer ]] && $local_enabled && [[ $local_model ]] && [[ $local_url ]]; then
-  $verbose && echo "Using Local AI LLM" > /dev/stderr
+localai() {
+  [[ $answer ]] && return
+  ! $localai_enabled && return
+  [[ ! $localai_model ]] && return
+  [[ ! $localai_url ]] && return
+  $verbose && echo "Using Local AI LLM with ${use_model:-$localai_model}" > /dev/stderr
   unset api_header_switch api_header
-  if [ -n "$local_api_key" ]; then
+  if [ -n "$localai_api_key" ]; then
     api_header_switch="-H "
-    api_header="Authorization: Bearer $local_api_key"
+    api_header="Authorization: Bearer $localai_api_key"
+  fi
+  if [ -n "$localai_prompt" ]; then
+    localai_prompt=${localai_prompt#\"}
+    localai_prompt="\"prompt\": \"${localai_prompt%\"}\","
   fi
   data="{
         \"max_tokens\": 8192,
-        \"prompt\": \"You are a helpful assistant. Do not show your thought process. Give a simple answer to the question. Reasoning: low\",
+        $localai_prompt
         \"messages\": [
           {
             \"role\": \"user\",
@@ -173,34 +182,39 @@ if [[ ! $answer ]] && $local_enabled && [[ $local_model ]] && [[ $local_url ]]; 
             \"content\": \"$user_message\"
           }
         ],
-        \"model\": \"${use_model:-$local_model}\"
+        \"model\": \"${use_model:-$localai_model}\"
       }"
   $debug && echo "$data" > /dev/stderr
-  tmpanswer=$(curl -s $local_url/v1/chat/completions $api_header_switch"$api_header" \
+  tmpanswer=$(curl -s $localai_url/v1/chat/completions $api_header_switch"$api_header" \
     -H "content-type: application/json" -d "$data")
   $debug && echo "Local AI output: $tmpanswer" > /dev/stderr
-  tmpanswer=$(echo "$tmpanswer" | jq -r '.choices[0].message.reasoning')
+  tmpanswer=$(echo "$tmpanswer" | jq -r '.choices[0].message.reasoning // .choices[0].message.content')
   $debug && echo "Local AI post-jq output: $tmpanswer" > /dev/stderr
-  tmpanswer=$(echo "$tmpanswer" | grep -oE '\b[A-Za-z]*day\b' | tail -n1)
+  tmpanswer=$(echo "$tmpanswer" | grep -oE '\b([Ss]un|[Mm]on|[Tt]ues|[Ww]ednes|[Tt]hurs|[Ff]ri|[Ss]atur)day\b' | tail -n1)
 
   unset api_header_switch api_header
   if [[ $tmpanswer ]]; then
     $verbose && echo "Local AI answer: $tmpanswer" > /dev/stderr
-    answers[local]=$tmpanswer
+    answers[localai]=$tmpanswer
     answer=$(check_agreement)
     [ $? != 0 ] && $debug && echo "No agreement after ${!answers[@]}"
   fi
-fi
+}
 
-if [[ ! $answer ]] && $ollama_enabled && [[ $ollama_model ]] && [[ $ollama_url ]]; then
-  $verbose && echo "Using Ollama LLM" > /dev/stderr
+ollama() {
+  [[ $answer ]] && return
+  ! $ollama_enabled && return
+  [[ ! $ollama_model ]] && return
+  [[ ! $ollama_url ]] && return
+
+  $verbose && echo "Using Ollama LLM with ${use_model:-$ollama_model}" > /dev/stderr
   unset api_header_switch api_header
   if [ -n "$ollama_api_key" ]; then
     api_header_switch="-H "
     api_header="Authorization: Bearer $ollama_api_key"
   fi
   data="{
-        \"model\": \"$ollama_model\",
+        \"model\": \"${use_model:-$ollama_model}\",
         \"prompt\": \"$user_message\",
         \"stream\": false
       }"
@@ -209,7 +223,7 @@ if [[ ! $answer ]] && $ollama_enabled && [[ $ollama_model ]] && [[ $ollama_url ]
   $debug && echo "Ollama output: $tmpanswer" > /dev/stderr
   tmpanswer=$(echo "$tmpanswer" | jq -r '.response')
   $debug && echo "Ollama post-jq output: $tmpanswer" > /dev/stderr
-  tmpanswer=$(echo "$tmpanswer" | grep -oE '\b[A-Za-z]*day\b' | tail -n1)
+  tmpanswer=$(echo "$tmpanswer" | grep -oE '\b([Ss]un|[Mm]on|[Tt]ues|[Ww]ednes|[Tt]hurs|[Ff]ri|[Ss]atur)day\b' | tail -n1)
 
   unset api_header_switch api_header
   if [[ $tmpanswer ]]; then
@@ -218,20 +232,28 @@ if [[ ! $answer ]] && $ollama_enabled && [[ $ollama_model ]] && [[ $ollama_url ]
     answer=$(check_agreement)
     [ $? != 0 ] && $debug && echo "No agreement after ${!answers[@]}"
   fi
-fi
+}
 
-if [[ ! $answer ]] && $mistral_enabled && [[ $mistral_api_key ]] && [[ $mistral_agent_id ]]; then
+mistral() {
+  [[ $answer ]] && return
+  ! $mistral_enabled && return
+  [[ ! $mistral_api_key ]] && return
+  [[ ! $mistral_agent_id ]] && return
   $verbose && echo "Using Mistral LLM" > /dev/stderr
   [ -z "$mistral_api_key" ] && echo "Error: Cannot use Mistral: No API key in $secrets_file" && exit 1
-  tmpanswer=$(curl -s https://api.mistral.ai/v1/conversations \
-    -H "Content-Type: application/json" \
-    -H "Authorization: Bearer $mistral_api_key" \
-    -d "{
+  data="{
           \"agent_id\": \"$mistral_agent_id\",
           \"inputs\": [
             {\"role\":\"user\",\"content\":\"$user_message\"}
           ]
-    }" | jq -r '.outputs[0].content' | grep -oE '\b[A-Za-z]*day\b' | tail -n1)
+        }"
+  tmpanswer=$(curl -s https://api.mistral.ai/v1/conversations \
+    -H "Content-Type: application/json" \
+    -H "Authorization: Bearer $mistral_api_key" -d "$data")
+  $debug && echo "Mistral output: $tmpanswer" > /dev/stderr
+  tmpanswer=$(echo "$tmpanswer" | jq -r '.outputs[0].content')
+  $debug && echo "Mistral post-jq output: $tmpanswer" > /dev/stderr
+  tmpanswer=$(echo "$tmpanswer" | grep -oE '\b([Ss]un|[Mm]on|[Tt]ues|[Ww]ednes|[Tt]hurs|[Ff]ri|[Ss]atur)day\b' | tail -n1)
 
   if [[ $tmpanswer ]]; then
     $verbose && echo "Mistral answer: $tmpanswer" > /dev/stderr
@@ -239,22 +261,30 @@ if [[ ! $answer ]] && $mistral_enabled && [[ $mistral_api_key ]] && [[ $mistral_
     answer=$(check_agreement)
     [ $? != 0 ] && $debug && echo "No agreement after ${!answers[@]}"
   fi
-fi
+}
 
-if [[ ! $answer ]] && $claude_enabled && [[ $claude_api_key ]]; then
+claude() {
+  [[ $answer ]] && return
+  ! $claude_enabled && return
+  [[ ! $claude_model ]] && return
+  [[ ! $claude_api_key ]] && return
   $verbose && echo "Using Claude LLM" > /dev/stderr
   [ -z "$claude_api_key" ] && echo "Error: Cannot use Claude: No API key in $secrets_file" && exit 1
-  tmpanswer=$(curl -s https://api.anthropic.com/v1/messages \
-    -H "x-api-key: $claude_api_key" \
-    -H "anthropic-version: 2023-06-01" \
-    -H "content-type: application/json" \
-    -d "{
-          \"model\": \"claude-sonnet-4-20250514\",
+  data="{
+          \"model\": \"$claude_model\",
           \"max_tokens\": 100,
           \"messages\": [
             {\"role\": \"user\", \"content\": \"$user_message\"}
           ]
-    }" | jq -r '.content[0].text' | grep -oE '\b[A-Za-z]*day\b' | tail -n1)
+        }"
+  tmpanswer=$(curl -s https://api.anthropic.com/v1/messages \
+    -H "x-api-key: $claude_api_key" \
+    -H "anthropic-version: 2023-06-01" \
+    -H "content-type: application/json" -d "$data")
+  $debug && echo "Claude output: $tmpanswer" > /dev/stderr
+  tmpanswer=$(echo "$tmpanswer" | jq -r '.content[0].text')
+  $debug && echo "Claude post-jq output: $tmpanswer" > /dev/stderr
+  tmpanswer=$(echo "$tmpanswer" | grep -oE '\b([Ss]un|[Mm]on|[Tt]ues|[Ww]ednes|[Tt]hurs|[Ff]ri|[Ss]atur)day\b' | tail -n1)
 
   if [[ $tmpanswer ]]; then
     $verbose && echo "Claude answer: $tmpanswer" > /dev/stderr
@@ -262,18 +292,26 @@ if [[ ! $answer ]] && $claude_enabled && [[ $claude_api_key ]]; then
     answer=$(check_agreement)
     [ $? != 0 ] && $debug && echo "No agreement after ${!answers[@]}"
   fi
-fi
+}
 
-if [[ ! $answer ]] && $chatgpt_enabled && [[ $chatgpt_api_key ]]; then
+chatgpt() {
+  [[ $answer ]] && return
+  ! $chatgpt_enabled && return
+  [[ ! $chatgpt_model ]] && return
+  [[ ! $chatgpt_api_key ]] && return
   $verbose && echo "Using ChatGPT LLM" > /dev/stderr
   [ -z "$chatgpt_api_key" ] && echo "Error: Cannot use ChatGPT: No API key in $secrets_file" && exit 1
+  data="{
+          \"model\": \"$chatgpt_model\",
+          \"input\": \"$user_message\"
+        }"
   tmpanswer=$(curl -s https://api.openai.com/v1/responses \
     -H "Content-Type: application/json" \
-    -H "Authorization: Bearer $chatgpt_api_key" \
-    -d "{
-          \"model\": \"gpt-5-mini\",
-          \"input\": \"$user_message\"
-    }" | jq -r '.output[0].content[0].text' | grep -oE '\b[A-Za-z]*day\b' | tail -n1)
+    -H "Authorization: Bearer $chatgpt_api_key" -d "$data")
+  $debug && echo "Claude output: $tmpanswer" > /dev/stderr
+  tmpanswer=$(echo "$tmpanswer" | jq -r '.output[0].content[0].text')
+  $debug && echo "Claude post-jq output: $tmpanswer" > /dev/stderr
+  tmpanswer=$(echo "$tmpanswer" | grep -oE '\b([Ss]un|[Mm]on|[Tt]ues|[Ww]ednes|[Tt]hurs|[Ff]ri|[Ss]atur)day\b' | tail -n1)
 
   if [[ $tmpanswer ]]; then
     $verbose && echo "ChatGPT answer: $tmpanswer" > /dev/stderr
@@ -281,7 +319,14 @@ if [[ ! $answer ]] && $chatgpt_enabled && [[ $chatgpt_api_key ]]; then
     answer=$(check_agreement)
     [ $? != 0 ] && $debug && echo "No agreement after ${!answers[@]}"
   fi
-fi
+}
+
+# Execute functions for LLMS
+localai
+ollama
+mistral
+claude
+chatgpt
 
 if [[ $answer ]]; then
   if $output_json; then
