Add Gemini, clean up order, add deafult models

diff --git a/bin/get_recycle_day_adjustment b/bin/get_recycle_day_adjustment
--- a/bin/get_recycle_day_adjustment
+++ b/bin/get_recycle_day_adjustment
@@ -4,19 +4,26 @@ for f in curl jq; do
   ! command -v $f &> /dev/null && echo "Error: The '$f' command is required" > /dev/stderr && exit 1
 done
 
-supported_engines="localai|ollama|chatgpt|claude|mistral"
+supported_engines="chatgpt|claude|gemini|localai|mistral|ollama"
 debug="${debug:-false}"
 extra_debug="${extra_debug:-false}"
 verbose="${verbose:-false}"
 extra_verbose="${extra_verbose:-false}"
 output_json="${output_json:-false}"
 today_date="$(date "+%Y-%m-%d")"
-chatgpt_url="${chatgpt_url:-https://api.openai.com/v1/responses}"
-claude_url="${claude_url:-https://api.anthropic.com/v1/messages}"
-claude_max_tokens="${claude_max_tokens:-100}"
-mistral_url="${mistral_url:-https://api.mistral.ai/v1/conversations}"
-anthropic_version="${anthropic_version:-2023-06-01}"
+
 engine_order="${engine_order:-localai ollama chatgpt claude mistral}"
+chatgpt_url="${chatgpt_url:-https://api.openai.com/v1/responses}"
+chatgpt_model="${chatgpt_model:-gpt-5-mini}"
+claude_url="${claude_url:-https://api.anthropic.com/v1/messages}"
+claude_model="${claude_model:-claude-sonnet-4-20250514}"
+claude_max_tokens="${claude_max_tokens:-100}"
+anthropic_version="${anthropic_version:-2023-06-01}"
+gemini_url="${gemini_url:-https://generativelanguage.googleapis.com/v1beta/models/%%MODEL%%:generateContent}"
+gemini_model="${gemini_model:-gemini-3-flash-preview}"
+gemini_thinking_level="${gemini_thinking_level:-low}"
+mistral_url="${mistral_url:-https://api.mistral.ai/v1/conversations}"
+mistral_model="${mistral_model:-mistral-medium-latest}"
 
 secrets_file="${secrets_file:-$(readlink -f $(dirname "$0")/../secrets.yaml)}"
 
@@ -41,7 +48,7 @@ for var in home_assistant_base_url recycle_url_main recycle_default_day ; do
 done
 
 # Get program settings that do not overwrite previous values
-for var in hass_api_key min_agree localai_enabled localai_url localai_model localai_prompt localai_api_key ollama_enabled ollama_url ollama_model ollama_api_key chatgpt_enabled chatgpt_model chatgpt_api_key claude_enabled claude_model claude_api_key mistral_enabled mistral_api_key mistral_agent_id ; do
+for var in hass_api_key min_agree localai_enabled localai_url localai_model localai_prompt localai_api_key ollama_enabled ollama_url ollama_model ollama_api_key chatgpt_enabled chatgpt_api_key claude_enabled claude_api_key gemini_enabled gemini_api_key mistral_enabled mistral_api_key mistral_agent_id ; do
   [[ ! "${!var}" ]] && declare "$var=$(awk "/^recycle_day_$var ?:/{sub(/^[^:]+ *: */,\"\");gsub(/^\"|\"$/,\"\");print;exit}" "$secrets_file")"
   declare "$var=${!var# }"  # Trim space
   declare "$var=${!var% }"  # Trim space
@@ -55,7 +62,7 @@ done
 [[ $answer ]] && min_agree=1 && answers[manual]=$answer
 
 # Get program settings that do overwrite previous values
-for var in engine_order localai_max_tokens localai_match ollama_max_tokens ollama_match chatgpt_url chatgpt_max_tokens chatgpt_match claude_max_tokens claude_url claude_match mistral_url mistral_max_tokens mistral_match ; do
+for var in engine_order localai_max_tokens localai_match ollama_max_tokens ollama_match chatgpt_url chatgpt_model chatgpt_max_tokens chatgpt_match claude_url claude_model claude_max_tokens claude_match gemini_url gemini_model gemini_thinking_level gemini_match mistral_url mistral_model mistral_max_tokens mistral_match ; do
   tmpval=$(awk "/^recycle_day_$var ?:/{sub(/^[^:]+ *: */,\"\");gsub(/^\"|\"$/,\"\");print;exit}" "$secrets_file")
   [[ $tmpval ]] && declare "$var=$tmpval"
   declare "$var=${!var# }"  # Trim space
@@ -266,7 +273,7 @@ day_search='\b([Ss]un|[Mm]on|[Tt]ues|[Ww]ednes|[Tt]hurs|[Ff]ri|[Ss]atur)day\b'
 # If debug mode, print variables
 if $debug; then
   echo "Settings: " > /dev/stderr
-  for var in secrets_file home_assistant_base_url hass_api_key recycle_url_main county_alert_url recycle_default_day normal_recycle_day today_date reference_date reference_ymd min_agree user_message engine_order localai_enabled localai_url localai_model local_ai_max_tokens localai_prompt localai_api_key localai_match ollama_enabled ollama_url ollama_model ollama_max_tokens ollama_api_key ollama_match chatgpt_enabled chatgpt_model chatgpt_max_tokens chatgpt_api_key chatgpt_match claude_enabled claude_model claude_max_tokens claude_api_key claude_match mistral_enabled mistral_max_tokens mistral_api_key mistral_agent_id mistral_match ; do
+  for var in secrets_file home_assistant_base_url hass_api_key recycle_url_main county_alert_url recycle_default_day normal_recycle_day today_date reference_date reference_ymd min_agree user_message engine_order localai_enabled localai_url localai_model local_ai_max_tokens localai_prompt localai_api_key localai_match ollama_enabled ollama_url ollama_model ollama_max_tokens ollama_api_key ollama_match chatgpt_enabled chatgpt_model chatgpt_max_tokens chatgpt_api_key chatgpt_match claude_enabled claude_model claude_max_tokens claude_api_key claude_match gemini_enabled gemini_model gemini_api_key mistral_enabled mistral_max_tokens mistral_api_key mistral_agent_id mistral_match ; do
     [ $var = user_message ] && printf ' - %s = "%s"\n' "$var" "$(echo "${!var}" | fold -sw $((COLUMNS - ${#var} - 3))|sed "2,\$s/^/$(printf '%*s' $((${#var} - 3)))/")" > /dev/stderr
     ! [ $var = user_message ] && printf ' - %s = "%s"\n' "$var" "${!var}" > /dev/stderr
   done
@@ -309,10 +316,13 @@ run_engine() {
   local prompt="${engine}_prompt"
   local engine_url="${engine}_url"
   local engine_model="${engine}_model"
+  local t
+  [ -n "${!engine_model}" ] && t="${!engine_url}";declare "${engine}_url=${t//%%MODEL%%/${!engine_model}}"; unset t
   local engine_match="${engine}_match"
   local engine_api_key engine_agent_id
   [ -v "${engine}_api_key" ] && engine_api_key="${engine}_api_key"
   [ -v "${engine}_agent_id" ] && engine_agent_id="${engine}_agent_id"
+  [ -n "${!engine_agent_id}" ] && unset engine_model
   $verbose && echo "Using $engine LLM${!engine_model:+ with ${!engine_model}}${!engine_agent_id:+ with an engine agent id}" > /dev/stderr
 
   local api_header_switch api_header add_header_switch add_header message_content
@@ -325,62 +335,108 @@ run_engine() {
         add_header_switch="-H "
         add_header="anthropic-version: $anthropic_version"
         ;;
+      gemini)
+        api_header="x-goog-api-key: ${!engine_api_key}"
+        ;;
       *) api_header="Authorization: Bearer ${!engine_api_key}" ;;
     esac
   fi
   case "$engine" in
-    localai)
-      message_content="\"messages\": [
-          {
-            \"role\": \"user\",
-            \"reasoning\": \"low\",
-            \"content\": \"$user_message\"
-          }
-        ]"
-      message_content=$(jq -n --arg message "$user_message" '{messages:[{role:"user",reasoning:"low",content:$message}]}')
-      ;;
-    ollama)
-      message_content="\"prompt\": \"$user_message\",
-        \"stream\": false"
-      message_content=$(jq -n --arg message "$user_message" '{prompt:$message,stream:false}')
-      ;;
     chatgpt)
-      message_content="\"input\": \"$user_message\""
-      message_content=$(jq -n --arg message "$user_message" '{input:$message}')
+      message_content='{
+        "input": $user_message
+      }'
       ;;
     claude)
-      message_content="\"messages\": [
+      message_content='{
+        "messages": [
           {
-            \"role\": \"user\",
-            \"content\": \"$user_message\"
+            "role": "user",
+            "content": $user_message
           }
-        ]"
-      message_content=$(jq -n --arg message "$user_message" '{messages:[{role:"user",content:$message}]}')
+        ]
+      }'
+      ;;
+    gemini)
+      message_content='{
+        "contents": [
+          {
+            "parts": [
+              {
+                "text": $user_message
+              }
+            ]
+          }
+        ]
+      }'
+      # Determine if model supports thinking (and is gemini-3)
+      if [[ ${!engine_model} =~ ^gemini-[3-9] ]]; then
+        t="${!engine_url}"
+        t=${t%:*Content}
+        thinking=$(curl -s "$t?key=${!engine_api_key}" | jq -r '.thinking')
+        [ "$thinking" != true ] && thinking=false
+
+        $thinking && [ -n "$gemini_thinking_level" ] && \
+        message_content=$({
+            jq -n --arg user_message "$user_message" "$message_content"
+            jq -n '{
+            "generationConfig": {
+              "thinkingConfig": {
+                "thinkingLevel": "'${gemini_thinking_level:-low}'"
+              }
+            }
+          }'
+          } | jq -s add)
+      fi
+      ;;
+    localai)
+      message_content='{
+        "messages": [
+          {
+            "role": "user",
+            "reasoning": "'${localai_reasoning_level:-low}'",
+            "content": $user_message
+          }
+        ]
+      }'
       ;;
     mistral)
-      message_content="\"inputs\": [
+      message_content='{
+        "inputs": [
           {
-            \"role\": \"user\",
-            \"content\": \"$user_message\"
+            "role": "user",
+            "content": $user_message
           }
-        ]"
-      message_content=$(jq -n --arg message "$user_message" '{inputs:[{role:"user",content:$message}]}')
+        ]
+      }'
+      if [ -n "${!engine_agent_id}" ]; then
+        message_content=$({
+          jq -n --arg user_message "$user_message" "$message_content"
+          jq -n '{"agent_id": "'${!engine_agent_id}'"}'
+        } | jq -s add)
+      fi
+      ;;
+    ollama)
+      message_content='{
+        "stream": false,
+        "prompt": $user_message
+      }'
       ;;
   esac
+  [ -z "$message_content" ] && echo "Error: Could not generate message_content for LLM" && exit 1
+  message_content=$(jq -n --arg user_message "$user_message" "$message_content")
 
   local data=$(jq -n \
     --arg max_tokens "${!max_tokens}" \
     --arg prompt "${!prompt}" \
-    --arg model "${use_model:-${!engine_model}}" \
-    --arg agent_id "${!engine_agent_id}" \
+    --arg model "${!engine_model}" \
     'if $model != "" then . + {model: $model} else . end
-    | if $agent_id != "" then . + {agent_id: $agent_id} else . end
     | if $max_tokens != "" then . + {max_tokens: ($max_tokens|tonumber)} else . end
     | if $prompt != "" then . + {prompt: $prompt} else . end
     ')
   [[ "$data" == "null" ]] && data="{}"
   data=$(jq -s '.[0] * .[1]' <(echo $data) <(echo "$message_content"))
-  $debug && echo "$data" > /dev/stderr
+  $debug && { echo "JSON data for curl:" && echo "$data" | sed 's/^/  /'; } > /dev/stderr
   $debug && set -x
   local tmpanswer=$(curl -s "${!engine_url}" \
     $api_header_switch${api_header:+"$api_header"} $add_header_switch${add_header:+"$add_header"} \
